import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner";
import Card from "../components/card";

import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStoresData,
    },
  };
}

export default function Home(props) {
  // const handleOnBannerButtonClick = () => {};
  const handleOnBannerButtonClick = () => {
    const coffeeStoresShops = document.getElementById("coffee-stores");
    coffeeStoresShops.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>coffee compass | find coffee near you!</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <Banner
            buttonText='view shops nearby'
            handleOnClick={handleOnBannerButtonClick}
          />
          {props.coffeeStoresData.length > 0 ? (
            <>
              <h2 id='coffee-stores' className={styles.heading2}>
                virginia beach coffee shops
              </h2>
              <div className={styles.cardLayout}>
                {props.coffeeStoresData.map((coffeeStore) => {
                  return (
                    <Card
                      key={coffeeStore.id}
                      shopName={coffeeStore.shopName}
                      imgURL={coffeeStore.imgURL}
                      href={`/coffee-store/${coffeeStore.id}`}
                      className={styles.card}
                    />
                  );
                })}
              </div>
            </>
          ) : (
            <h2 className={styles.heading2}>
              sorry... no coffee shops found :(
            </h2>
          )}
        </main>
      </div>
    </>
  );
}
