import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";

export default function Home() {
  const handleOnBannerButtonClick = () => {
    console.log("Banner button clicked!");
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>coffee compass | find coffee near you!</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <Banner
            buttonText='view shops nearby'
            handleOnClick={handleOnBannerButtonClick}
          />
        </main>
      </div>
    </>
  );
}
